### ISSUE TITLE
Burning bootloader: msglen 8912897 exceeds max message size 100000

### ISSUE THREAD

**Issue by Miraculix200** [SpenceKonde/jtag2updi#5]
Serial board: FTDI Basic 3.3V
Programmer board: Arduino Pro Mini 3.3V 8MHz (clone)
Target MCU: AVR128DB32 (original from Microchip)
Bootloader burning method: Arduino IDE

It looks like avrdude fails at communicating with the jtag2updi programmer at a certain stage in the "burn bootloader" process. I get this output from Arduino IDE:

```
JTAG ICE mkII sign-on message:
Communications protocol version: 1
...
Vtarget         : 5.0 V
avrdude: jtagmkII_recv(): msglen 135135233 exceeds max message size 100000, ignoring message
avrdude: jtagmkII_recv(): msglen 135135233 exceeds max message size 100000, ignoring message
avrdude: jtagmkII_recv(): msglen 135135233 exceeds max message size 100000, ignoring message
avrdude: jtagmkII_recv(): msglen 135135233 exceeds max message size 100000, ignoring message
avrdude: jtagmkII_set_devdescr(): timeout/error communicating with programmer (status -1)
avrdude: jtagmkII_initialize(): Cannot locate "flash" and "boot" memories in description
avrdude: jtagmkII_reset(): timeout/error communicating with programmer (status -1)
avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.

avrdude: jtagmkII_close(): timeout/error communicating with programmer (status -1)
```

What I've tried to fix the problem:

- Connect 10uF electrolytic capacitor between RST and GND
- Connect 100 or 220 Ohm resistor between RST and VCC (3.3V)
- Remove DTR and push reset button randomly
- #define F_CPU 8000000U
- #define UPDI_BAUD 80000U // (max 225000 min approx. F_CPU/100)

Nothing fixes the problem.  Changing the baud rate and CPU speed was most likely useless, as I get the same output when there is no UPDI connection present. It just takes a little longer until it shows the error messages.

The AVR128DB32 is actually alive however, as I was able to flash the DxCore bootloader using pyupdi and set fuses through pymcuprog. Now I can upload sketches via Arduino IDE.  

Is it actually possible to use jtag2updi on a 3.3V Arduino Pro Mini running at 8MHz?

Edit: If I remember correctly I had the same problem with ATmega4808

**Comment by amadeuspzs** [comment]
I have the same issue with an ATMega328P at 8MHz.

Strange thing is I had it working previously.

I'll try a few chips to see I can pinpoint what's going wrong

**Comment by amadeuspzs** [comment]
I've confirmed this is an issue with https://github.com/ElTangas/jtag2updi as well so probably not an issue with this repo.

At first I thought I'd fried the target chip, but it still flashes with the pyupdi approach.

I have tried another ATMega328P with an external 8MHz crystal and same problem.

@Eltangas states `8MHz also works but is less reliable` - I don't have a higher frequency chip to try but could be worth a shot.

Also see `I have set the jtag2updi entry on the avrdude configuration file to run at 115200 baud by default. This baud rate can cause errors if, for example, your MCU is running at 8MHz`

Aha! By adding `-b 57600` to the `avrdude.conf` I have a working connection:

`avrdude -C avrdude.conf -c jtag2updi -p t1614 -P /dev/tty.usbserial-AQ00K54V -b 57600`

So now to figure out how to change this in the Arduino IDE...

**Comment by amadeuspzs** [comment]
Solved! 

If you change https://github.com/SpenceKonde/megaTinyCore/blob/master/megaavr/avrdude.conf#L17099 to `57600` it works a treat at 8 MHz 😅 

@SpenceKonde this issue can probably be closed/migrated to megaTinyCore - can you include an option to select baud rate when using jtag2updi for those of us with 8 MHz programmers?

**Comment by SpenceKonde** [comment]
It works at 57.6 without u2x? sigh... surprising, that is; I'd have thought you need U2X for that to work.. Note that it works no problem with a modern AVR at 8MHz 3.3v just not the classic ones.. 
Depending on a godawful unmaintainable firmware, and a godawful nearly-unmaintained tool (avrdude), jtag2updi is not a winning programming solution. And in fact,  jtag2updi _is no longer a recommended programming method for megaTinyCore._ With 2.3.2, the pymcuprog-based serial adapter as programmer is now  faster (8-20x faster than in previous versions, and 3-4 times faster than jtag2updi), cheaper, and doesn't have this million file disaster area of a piece of firmware that it relies on....

**Comment by SpenceKonde** [comment]
Maintenance (by me at least) is done. Finished. Irt is a legacy programming option that is not the subject ongoing development no planned futurre development. 



Users are advised to transition to SerialUPDI.
