### ISSUE TITLE
support for attiny 2. series (solved)

### ISSUE THREAD

**Issue by DanSkareda** [SpenceKonde/jtag2updi#6]
Hi. I can't compile this code (jtag2updi - my circuit is for HV programming) for attiny 2. series (my MCU is attiny1624). Compiler error: "HOST_USART was not declared in this scope". I thing - this MCU appears to be identified as XAVR.
Can you help me with advice or fix the code?
(On attiny1604 and attiny1614 is compile OK) 
Thanks, Dan.

**Comment by DanSkareda** [comment]
In parts.h I changed it like this. Compile for attiny1624 is without error. Is it OK?

#if  (defined(__AVR_ATtiny3217__) || defined(__AVR_ATtiny1617__) || defined(__AVR_ATtiny1604__) || defined(__AVR_ATtiny1607__) || \
      defined(__AVR_ATtiny3216__) || defined(__AVR_ATtiny1616__) || defined(__AVR_ATtiny1606__) || defined(__AVR_ATtiny1614__) || defined(__AVR_ATtiny1624__))

**Comment by DanSkareda** [comment]
Not OK. When I uncomment HV programming mode, compile ends with errors...

**Comment by DanSkareda** [comment]
I compared the 1st series and 2nd series datasheets and found that they differ in ADC. So I rewrote the code in SYS.CPP, SYS.H and PARTS.H. My HV programmer is already working properly. Solved.

**Comment by SpenceKonde** [comment]
Can you give me a PR for the HV programmer changes to support the new parts?

**Comment by DanSkareda** [comment]
These changes are for 1624 only. The code in sys.cpp replaces the code for 1614, so the code is then not universal. 

In "parts.h":

#if  (defined(__AVR_ATtiny3217__) || defined(__AVR_ATtiny1617__) || defined(__AVR_ATtiny1604__) || defined(__AVR_ATtiny1607__) || defined(__AVR_ATtiny3216__) || defined(__AVR_ATtiny1616__) || defined(__AVR_ATtiny1606__) || defined(__AVR_ATtiny1614__) || defined(__AVR_ATtiny1624__))

      #define __AVR_ATtiny_Zero_One__

In "sys.h" I enabled:

#define USE_HV_PROGRAMMING

In "sys.cpp":

uint8_t SYS::checkHVMODE() {                         // Check HV Programming Mode Switch
  #if defined(USE_HV_PROGRAMMING)
#if defined(__AVR_ATmega328P__)                      // Arduino Nano
  ADCSRA =  (1 << ADEN);                             // turn ADC on
  ADCSRA |= (1 << ADPS0) | (1 << ADPS2);             // prescaler of 32
  ADMUX = (1 << REFS0) | (1 << ADLAR) | (7 & 0x07);  // use AVcc reference, 8-bit result, select A7
  ADCSRA  |= (1 << ADSC);                            // start a conversion
  while (ADCSRA &  (1 << ADSC));                     // wait while busy
  return ADCH;                                       // return HV mode jumper setting
#elif defined(__AVR_ATtiny_Zero_One__)
  PORTA_PIN1CTRL = 0x04;                             // disable digital input buffer for PA1
  ADC0_CTRLA |= ADC_ENABLE_bm;                       // turn ADC on
  ADC0_CTRLB = 0xB;                                  // prescaler of 32
  ADC0_CTRLC = ADC_REFSEL_VDD_gc;                    // use Vdd reference
  ADC0_COMMAND = 0x2;                                // start conversion by writting to muxpos, 8bit result, one measurement
  ADC0_MUXPOS = 0x01;                                // select AIN1
  while (ADC0_STATUS == 0);                          // wait while busy
  return ADC0_RESULT0;                               // return HV mode jumper setting

/* new version of the code, not yet tested  
  PORTA_PIN1CTRL = PORT_ISC_INPUT_DISABLE_gc;        // disable digital input buffer for PA1
  ADC0_CTRLA |= ADC_ENABLE_bm;                       // turn ADC on
  ADC0_CTRLB = ADC_PRESC_DIV32_gc;                   // prescaler of 32
  ADC0_CTRLC = ADC_REFSEL_VDD_gc;                    // use Vdd reference
  ADC0_COMMAND = ADC_START_MUXPOS_WRITE_gc;          // start conversion by writting to muxpos, 8bit result, one measurement
  ADC0_MUXPOS = ADC_MUXPOS_AIN1_gc;                  // select AIN1
  while (!(ADC0_STATUS & ADC_ADCBUSY_bm));           // wait while busy
  return ADC0_RESULT0; 
*/

**Comment by SpenceKonde** [comment]
Maintenance (by me at least) is done. Finished. Irt is a legacy programming option that is not the subject ongoing development no planned futurre development.

Users are advised to transition to SerialUPDI.
